### ISSUE TITLE
Proposal: Use git-chglog to replace github-changelog-generator

### ISSUE THREAD

**Issue by Xuanwo** [maintainer-org/maintainer#41]
Now we have golang implementations for CHANGELOG generator like [git-chglog/git-chglog](https://github.com/git-chglog/git-chglog).

If we migrate to `git-chglog`, we don't need to depend on ruby's github-changelog-generator any more.

**Comment by gaocegege** [comment]
SGTM

**Comment by Xuanwo** [comment]
I'm working on this proposal.
